version: '3.8'
services:
  stats-server:
    build: stats-server
    image: stats_server_image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-server
      - SPRING_DATASOURCE_USERNAME=statsadmin
      - SPRING_DATASOURCE_PASSWORD=iamstatsadmin

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-server
      - POSTGRES_USER=statsadmin
      - POSTGRES_PASSWORD=iamstatsadmin

    # ewm-service:
    #  build: main-service
    #  image: main-service-image
      #  ports:
    #  - "8080:8080"

    # ewm-db:
  #  image: postgres:14-alpine
